# Generated by Django 5.0.1 on 2024-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("price", "0002_alter_actiontype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontype",
            name="estimated_time",
            field=models.TimeField(verbose_name="Estimated time"),
        ),
    ]
